In [2]:
import torch
x = torch.empty(3)
print(x)

tensor([1.6928e+22, 2.6451e+20, 9.0999e+26])


In [3]:
x = torch.empty(2,3)
print(x)

tensor([[8.5052e+20, 3.2338e-41, 8.5106e+20],
        [3.2338e-41, 8.9683e-44, 0.0000e+00]])


In [4]:
x = torch.empty(2,3,4)
print(x)

tensor([[[ 3.2963e+07,  4.3879e-41,  8.5090e+20,  3.2338e-41],
         [ 4.4842e-44,  0.0000e+00,  8.9683e-44,  0.0000e+00],
         [-3.7299e+00,  3.2331e-41,  8.5126e+20,  3.2338e-41]],

        [[ 1.2612e-44, -1.7412e+38,  8.5127e+20,  3.2338e-41],
         [ 1.5624e-42,  0.0000e+00,  8.5126e+20,  3.2338e-41],
         [ 1.2612e-44,  9.3887e-44,  9.1084e-44,  0.0000e+00]]])


In [5]:
x = torch.rand(2,3)
print(x)

tensor([[0.8649, 0.9190, 0.0149],
        [0.6981, 0.1454, 0.2603]])


In [6]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x,y)
print(x+y)

tensor([[0.2777, 0.0943],
        [0.4136, 0.1894]]) tensor([[0.3685, 0.4615],
        [0.9317, 0.1781]])
tensor([[0.6462, 0.5557],
        [1.3453, 0.3674]])


In [10]:
z = torch.add(x,y)
print(z)

tensor([[0.6462, 0.5557],
        [1.3453, 0.3674]])


In [11]:
y.add_(x)

tensor([[0.6462, 0.5557],
        [1.3453, 0.3674]])

In [12]:
z = x-y
print(z)

tensor([[-0.3685, -0.4615],
        [-0.9317, -0.1781]])


In [13]:
z = torch.mul(x,y)
print(z)

tensor([[0.1795, 0.0524],
        [0.5565, 0.0696]])


In [14]:
z = x/y
print(z)

tensor([[0.4298, 0.1697],
        [0.3075, 0.5154]])


In [15]:
a = torch.rand(5,3)
print(a)

tensor([[0.8718, 0.8330, 0.4839],
        [0.6595, 0.1398, 0.6334],
        [0.5960, 0.3425, 0.4051],
        [0.2720, 0.7636, 0.0915],
        [0.1660, 0.8229, 0.1182]])


In [16]:
print(a[:,0])

tensor([0.8718, 0.6595, 0.5960, 0.2720, 0.1660])


In [17]:
print(a[1,1])

tensor(0.1398)


In [18]:
print(a[1,1].item())

0.1397985816001892


In [19]:
b = torch.rand(4,4)
print(b)

tensor([[0.8176, 0.9437, 0.9081, 0.4026],
        [0.4786, 0.4495, 0.7811, 0.5982],
        [0.3483, 0.4284, 0.5854, 0.3887],
        [0.1028, 0.8967, 0.4380, 0.6280]])


In [20]:
c = b.view(16)
print(c)

tensor([0.8176, 0.9437, 0.9081, 0.4026, 0.4786, 0.4495, 0.7811, 0.5982, 0.3483,
        0.4284, 0.5854, 0.3887, 0.1028, 0.8967, 0.4380, 0.6280])


In [21]:
c = b.view(-1,8)
print(c)

tensor([[0.8176, 0.9437, 0.9081, 0.4026, 0.4786, 0.4495, 0.7811, 0.5982],
        [0.3483, 0.4284, 0.5854, 0.3887, 0.1028, 0.8967, 0.4380, 0.6280]])


In [22]:
import numpy as np

In [23]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [24]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [25]:
a.add_(1)
print(a,type(a))
print(b, type(b))

tensor([2., 2., 2., 2., 2.]) <class 'torch.Tensor'>
[2. 2. 2. 2. 2.] <class 'numpy.ndarray'>


In [26]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b, type(b))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [27]:
a+=1

In [28]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  print(device,' available')
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x+y
  print(z)
  z = z.to("cpu")
  print(z, type(z))
else:
  print('Device NOT available')

cuda  available
tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.]) <class 'torch.Tensor'>


In [33]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


Gradient Calculation with Auto Grad

In [2]:
import torch
x = torch.randn(3,requires_grad=True)
print(x)

tensor([0.5494, 0.5208, 1.0962], requires_grad=True)


In [3]:
y = x+2
print(y)

tensor([2.5494, 2.5208, 3.0962], grad_fn=<AddBackward0>)
